console.log('Hello JavaScript')
console.log(9 + 9)
console.log('Jagadish', 999)
console.log('Web Development Learn With Sumit')
console.log('I operand with' + 'I am opreator')
console.log('I am coming from here')
console.log('one', 'two', 'three', 'four', 'five', 'six', 'seven')
console.log('three different systems for me')
console.log('hello javascript')